# Generated by Django 4.1.1 on 2023-09-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_address_myuser_age_myuser_code_meli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='company_history',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
