# Generated by Django 4.2.4 on 2023-11-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myuser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='passwordtxt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
