# Generated by Django 4.2.4 on 2023-11-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_myuser_passwordtxt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
