# Generated by Django 4.2.4 on 2023-11-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_myuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='company_history',
            field=models.TextField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='description',
            field=models.TextField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='skill',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
