# Generated by Django 4.2.4 on 2023-11-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_myuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='can_edit',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='p_access',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
