# Generated by Django 4.2.4 on 2023-11-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_myuser_can_edit_myuser_p_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='see_users',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
